### PR TITLE
ff2mpv.py: Add Python native client

### PR DESCRIPTION
**Pull request by kirill9000**
I think Python native client would be user-friendlier, since most Linux distros have Python installed out of the box.

### CODE REVIEW

**Comment by woodruffw** [comment]
Good idea, and thanks for the work!

Could you add a note to the "Usage" section of the README telling people about `ff2mpv.py`?

**Comment by kirill9000** [comment]
Done.

**Comment by woodruffw** [comment]
Thanks. I'll merge this in a bit.

**Comment by kirill9000** [comment]
Wait! Sorry, I've found small bug. Don't merge yet, I'll fix it.

**Comment by kirill9000** [comment]
There, should be good now. (Actually, bug didn't present itself, since we're sending and receiving ASCII anyway, but it would be cleaner with it fixed.)

**Comment by woodruffw** [comment]
Thanks!

**Pull request merged**
