### PR TITLE
Feature add install script for Windows

### PR DESCRIPTION
**Pull request by DanSM-5**
Windows installation script.

This should make installation a smooth process for windows users.
I made it to behave as the bash installation scripts.

Example:
`> .\install.ps1 firefox`
Will add the registry key for `ff2mpv` in the NativeMessagingHost for firefox.

Featured browsers
* Firefox
* Chrome
* Chromium
* Edge

Other features
* Allow custom installation for chromium based browsers
* Detect python command and update it in the batch script
* Generate a different JSON file for chromium browsers to avoid conflicts with firefox

### CODE REVIEW

**Comment by woodruffw** [comment]
Thanks for the PR!

Is there any functional overlap between this script and `check-config-win.py`? I believe another Windows user contributed that earlier script to manage the registry settings for ff2mpv.

Assuming there is some overlap, I'm not opposed to deleting that old script and completely replacing it with your work (especially since the old one doesn't support anything but Firefox).

**Comment by DanSM-5** [comment]
The python script does 3 things
* checks that `mpv` and the registry are in place
* add the registry key for firefox
* remove the registry key for firefox

It mainly overlaps with the installation part but only for firefox as the powershell script supports more browsers and will generate the JSON's for chromium based browsers.

I didn't add a command to just check the configuration (like checking for mpv). I added a check for python mainly because in windows this may vary and the batch script won't work unless it uses the right command in the specific system. It would be simple add a check for MPV and just log a message if it is not found. Would this be desired?

Finally, the powershell script only does installations but it won't add the registry key gain if it is already present or it will update the value if you move the location of the repository. I could later implement a flag to allow removing the key. Other changes are local to the repository (like creating a JSON or modifying the bat script) and follow the same conventions as the `sh` scrips to keep it consistent.

**Comment by DanSM-5** [comment]
I made an update so the powershell script:

* Add flag `-uninstall` to remove the ff2mpv key from the registry
* Add flag `-help` to show more information about the command to call the script
* Add a warning message in the install to notify the user that `mpv` could not be found

I believe that now the python script can be replaced and all its functions should be cover.

**Comment by woodruffw** [comment]
> I believe that now the python script can be replaced and all its functions should be cover.

Thank you! Would you mind deleting the Python script as part of this changeset?

I'll do a final review pass tonight as well, but this LGTM overall.

**Comment by DanSM-5** [comment]
Done. While at it I added option to display help or exit the prompt to make it more user friendly.

**Comment by woodruffw** [comment]
CI failure is caused by the deletion. Feel free to delete that line from the CI if you have a moment, otherwise I'll clean it up post-merge.

**Comment by DanSM-5** [comment]
No worries, I found where the configuration was. I removed the check for the script in ci.yml.

**Review by woodruffw — APPROVED** [review]

**Comment by woodruffw** [comment]
Thanks again!

**Comment by DanSM-5** [comment]
I'll update the wiki over the weekend with usage about the new installation script on Windows.

**Comment by woodruffw** [comment]
Sounds good, thanks for doing that.

**Pull request merged**
