### PR TITLE
Add install scripts for chromium

### PR DESCRIPTION
**Pull request by DanSM-5**
Added scripts to install ff2mpv-chromium.json for chromium and chrome in linux and mac.

The chrome version just pass an argument to the chromium script. It is the easier way I found to achieve this but I accept suggestions if adding two files is not desired.

### CODE REVIEW

**Comment by woodruffw** [comment]
Thanks for adding this! 

IMO we can skip the `install-chrome.sh` and just tell people to do `install-chromium.sh chrome` -- it's not worth a separate file. Otherwise looks good to me.

**Comment by DanSM-5** [comment]
got it, I removed the extra file.

**Comment by DanSM-5** [comment]
got it, I removed the extra file

**Review by woodruffw — APPROVED** [review]

**Comment by eNV25** [comment]
Should I make the scripts work with Brave too?

I recently started using Brave after I created the pull request for chromium. It's not too different from chromium and it uses the Chrome Web Store right now, so everything should just work.

Changed needed for that:

- package-chormium.sh: add case for command `brave` in PATH
- install-chromium.sh: add case for brave
  It uses `~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts` on linux. I am not sure about macOS because I don't have a mac.

I could look into other chromium based browsers like vivaldi and microsolft edge too.

I got interested when I created an AUR [package for ff2mpv-go](https://aur.archlinux.org/packages/ff2mpv-go-git/) for Arch Linux. I managed to add (untested) support for many browsers after finding the system-wide native messaging host manifest location for many browsers using the package repository's file database.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ff2mpv-go-git

**Comment by DanSM-5** [comment]
I have access to a mac. If you'd like, I can install Brave there and find the location for the `NativeMessagingHosts`  @eNV25. Would that be helpful?

**Comment by eNV25** [comment]
Yes, I couldn't find official resources for this.

**Comment by DanSM-5** [comment]
Ok, so it is as follows `~/Library/Application Support/BraveSoftware/Brave-Browser`. Here is where the `NativeMessagingHost` should be located @eNV25. I can confirm that the extension works on Brave on Mac.

**Pull request merged**
