### PR TITLE
Support Darwin in install script

### PR DESCRIPTION
**Pull request by Atemu**
Needs wiki docs update after merge.

### CODE REVIEW

**Comment by woodruffw** [comment]
This looks good, thanks! I'll do another pass and merge tonight.

**Comment by woodruffw** [comment]
...forgot to merge. Sorry. Doing it now.

**Comment by woodruffw** [comment]
Thanks again!

**Comment by Atemu** [comment]
I have updated the instructions in the wiki.

**Comment by woodruffw** [comment]
Thanks for doing that!

**Pull request merged**
